In [2]:
# Basic Python


In [ ]:
## 1. Split this string


In [ ]:
s = "Hi there Sam!"

In [3]:
a=s.split()
print(a)

['Hi', 'there', 'Sam!']


In [ ]:
## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [5]:
print("The diameter of {} is {} kilometers".format(planet,diameter))

The diameter of Earth is 12742 kilometers


In [6]:
## 3. In this nest dictionary grab the word "hello"

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d["k1"][3]["tricky"][3]["target"][3]

'hello'

In [8]:
# Numpy

In [9]:
import numpy as np

In [10]:
## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 five?

In [11]:
import numpy as np
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
import numpy as np
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [13]:
## 5. Create an array of all the even integers from 20 to 35

In [14]:
import numpy as np
a=np.arange(20,35,2)
print(a)

[20 22 24 26 28 30 32 34]


In [15]:
## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:

a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [18]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

In [19]:
# Pandas

In [20]:
## 8. Create a dataframe with 3 rows and 2 columns

In [21]:
import pandas as pd

In [22]:

d1={"names":["nancy","abi","barath"],"age":[18,19,20]}
df=pd.DataFrame


In [23]:
## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [24]:
pd.date_range(start="1/1/2023",end="10/02/2023")

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

In [25]:
## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [26]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists,columns=["s.no","name","age"])
print(df)

   s.no name  age
0     1  aaa   22
1     2  bbb   25
2     3  ccc   24
